// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwj4P0FKMZWQioLVAkZ4FhWKmglINJ67E',
    appId: '1:177022499640:web:13a37f1d98068a03735fcd',
    messagingSenderId: '177022499640',
    projectId: 'crypto-list-app-78c53',
    authDomain: 'crypto-list-app-78c53.firebaseapp.com',
    storageBucket: 'crypto-list-app-78c53.appspot.com',
    measurementId: 'G-X5C44RZ6F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1__SJpY1RN4SWBtDNfmYOVk-IwSZvF-Q',
    appId: '1:177022499640:android:17b4783eff46c39e735fcd',
    messagingSenderId: '177022499640',
    projectId: 'crypto-list-app-78c53',
    storageBucket: 'crypto-list-app-78c53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQQDedwoA8ZtB_ofELdtxIKqPOBaqHv84',
    appId: '1:177022499640:ios:e3d010272a97564f735fcd',
    messagingSenderId: '177022499640',
    projectId: 'crypto-list-app-78c53',
    storageBucket: 'crypto-list-app-78c53.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQQDedwoA8ZtB_ofELdtxIKqPOBaqHv84',
    appId: '1:177022499640:ios:e3d010272a97564f735fcd',
    messagingSenderId: '177022499640',
    projectId: 'crypto-list-app-78c53',
    storageBucket: 'crypto-list-app-78c53.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );
}
